--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/04/2019 23:46:38
-- Server version: 5.5.5-10.1.32-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE contas;

--
-- Drop table `cartao`
--
DROP TABLE IF EXISTS cartao;

--
-- Drop table `consolidado`
--
DROP TABLE IF EXISTS consolidado;

--
-- Drop table `movimentacao`
--
DROP TABLE IF EXISTS movimentacao;

--
-- Set default database
--
USE contas;

--
-- Create table `movimentacao`
--
CREATE TABLE movimentacao (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(20) DEFAULT NULL,
  descricao TEXT DEFAULT NULL,
  data DATE DEFAULT NULL,
  tipo VARCHAR(20) DEFAULT NULL,
  loja VARCHAR(20) DEFAULT NULL,
  valor DECIMAL(8, 2) DEFAULT NULL,
  status VARCHAR(20) DEFAULT NULL,
  id_cartao INT(11) UNSIGNED DEFAULT NULL,
  posicao INT(3) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 34,
AVG_ROW_LENGTH = 496,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `consolidado`
--
CREATE TABLE consolidado (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(20) DEFAULT NULL,
  valor VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `cartao`
--
CREATE TABLE cartao (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(20) DEFAULT NULL,
  numero VARCHAR(20) DEFAULT NULL,
  cvc VARCHAR(3) DEFAULT NULL,
  sigla VARCHAR(3) DEFAULT NULL,
  credito DECIMAL(8, 2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table movimentacao
--
INSERT INTO movimentacao VALUES
(1, 'teste', 'teste', '2019-04-19', 'gasto', NULL, 100.00, 'normal', 1, 1),
(2, 'teste2', NULL, '2019-05-09', 'gasto', NULL, 200.00, 'normal', 1, 1),
(3, 'virtua', NULL, '2019-04-01', 'gasto', NULL, 207.00, NULL, NULL, NULL),
(4, 'netflix', NULL, '2019-04-01', 'gasto', NULL, 45.90, NULL, NULL, NULL),
(5, 'm', NULL, '2019-04-01', 'gasto', NULL, 1500.00, NULL, NULL, NULL),
(6, 'fiesta', NULL, '2019-04-01', 'gasto', NULL, 531.60, NULL, NULL, NULL),
(7, 'vivo', NULL, '2019-04-01', 'gasto', NULL, 46.99, NULL, NULL, NULL),
(8, 'virtua', NULL, '2019-05-01', 'gasto', NULL, 207.00, NULL, NULL, NULL),
(9, 'netflix', NULL, '2019-05-01', 'gasto', NULL, 45.90, NULL, NULL, NULL),
(10, 'm', NULL, '2019-05-01', 'gasto', NULL, 1500.00, NULL, NULL, NULL),
(11, 'fiesta', NULL, '2019-05-01', 'gasto', NULL, 531.60, NULL, NULL, NULL),
(12, 'vivo', NULL, '2019-05-01', 'gasto', NULL, 46.99, NULL, NULL, NULL),
(13, 'virtua', NULL, '2019-06-01', 'gasto', NULL, 207.00, NULL, NULL, NULL),
(14, 'netflix', NULL, '2019-06-01', 'gasto', NULL, 45.90, NULL, NULL, NULL),
(15, 'm', NULL, '2019-06-01', 'gasto', NULL, 1500.00, NULL, NULL, NULL),
(16, 'fiesta', NULL, '2019-06-01', 'gasto', NULL, 531.60, NULL, NULL, NULL),
(17, 'vivo', NULL, '2019-06-01', 'gasto', NULL, 46.99, NULL, NULL, NULL),
(18, 'virtua', NULL, '2019-07-01', 'gasto', NULL, 207.00, NULL, NULL, NULL),
(19, 'netflix', NULL, '2019-07-01', 'gasto', NULL, 45.90, NULL, NULL, NULL),
(20, 'm', NULL, '2019-07-01', 'gasto', NULL, 1500.00, NULL, NULL, NULL),
(21, 'fiesta', NULL, '2019-07-01', 'gasto', NULL, 531.60, NULL, NULL, NULL),
(22, 'vivo', NULL, '2019-07-01', 'gasto', NULL, 46.99, NULL, NULL, NULL),
(23, 'virtua', NULL, '2019-08-01', 'gasto', NULL, 207.00, NULL, NULL, NULL),
(24, 'netflix', NULL, '2019-08-01', 'gasto', NULL, 45.90, NULL, NULL, NULL),
(25, 'm', NULL, '2019-08-01', 'gasto', NULL, 1500.00, NULL, NULL, NULL),
(26, 'fiesta', NULL, '2019-08-01', 'gasto', NULL, 531.60, NULL, NULL, NULL),
(27, 'vivo', NULL, '2019-08-01', 'gasto', NULL, 46.99, NULL, NULL, NULL),
(28, 'virtua', NULL, '2019-09-01', 'gasto', NULL, 207.00, NULL, NULL, NULL),
(29, 'netflix', NULL, '2019-09-01', 'gasto', NULL, 45.90, NULL, NULL, NULL),
(30, 'm', NULL, '2019-09-01', 'gasto', NULL, 1500.00, NULL, NULL, NULL),
(31, 'fiesta', NULL, '2019-09-01', 'gasto', NULL, 531.60, NULL, NULL, NULL),
(32, 'vivo', NULL, '2019-09-01', 'gasto', NULL, 46.99, NULL, NULL, NULL),
(33, 'save', NULL, '2019-04-01', 'save', NULL, 50.00, NULL, NULL, NULL);

-- 
-- Dumping data for table consolidado
--
INSERT INTO consolidado VALUES
(1, 'itau', '355.3'),
(2, 'inter', '0'),
(3, 'casa', '200'),
(4, 'savings', '1500'),
(5, 'salario', '5600'),
(6, 'mensal', '340'),
(7, 'mes_atual', '04/2019'),
(8, 'semana_atual', '2');

-- 
-- Dumping data for table cartao
--
INSERT INTO cartao VALUES
(1, 'itauCredito', '4893.9102.0071.2364', '818', 'ivp', 25000.00),
(2, 'Nubank', '5234.2130.8938.2200', '171', 'n', 6000.00),
(3, 'Digio', '4589.1905.0756.8137', '820', 'd', 4750.00);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;